# Generated by Django 5.2.5 on 2025-11-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesionales/')),
                ('estado', models.BooleanField(default=True)),
                ('disponibilidad', models.CharField(max_length=200)),
                ('consultorio', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('dias_disponibles', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='profesionales.especialidad')),
                ('servicios', models.ManyToManyField(blank=True, related_name='profesionales', to='servicios.servicio')),
            ],
        ),
    ]
