# Generated by Django 5.2.5 on 2025-11-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='profesional',
            name='tipo_consulta',
            field=models.CharField(choices=[('PRES', 'Presencial'), ('TELE', 'Teleconsulta'), ('AMBOS', 'Ambos')], default='PRES', max_length=5),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='profesionales', to='profesionales.servicio'),
        ),
    ]
