# Generated by Django 5.2.8 on 2025-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_alter_especialidad_options_alter_profesional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='tipo_consulta',
            field=models.CharField(choices=[('PRES', 'Presencial'), ('TELE', 'Teleconsulta'), ('AMBOS', 'Hibrida')], default='PRES', max_length=5),
        ),
    ]
