# Generated by Django 5.2.8 on 2025-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_alter_profesional_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
