# Generated by Django 5.2.8 on 2025-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_profesional_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='piso',
            field=models.IntegerField(),
        ),
    ]
