# Generated by Django 5.2.8 on 2025-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_alter_profesional_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='profesionales.servicio'),
        ),
    ]
