# Generated by Django 5.2.5 on 2026-02-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pacientes',
        ),
    ]
