from profesionales.models import Especialidad, Profesional, Servicio

# === ESPECIALIDADES ===
especialidades = [
    {"nombre": "Cardiología", "descripcion": "Diagnóstico y tratamiento de enfermedades del corazón."},
    {"nombre": "Dermatología", "descripcion": "Atención de afecciones de la piel, uñas y cabello."},
    {"nombre": "Pediatría", "descripcion": "Cuidado de la salud en niños y adolescentes."},
    {"nombre": "Ginecología", "descripcion": "Salud reproductiva y control ginecológico."},
    {"nombre": "Neurología", "descripcion": "Diagnóstico y tratamiento de trastornos del sistema nervioso."},
    {"nombre": "Traumatología", "descripcion": "Lesiones óseas, musculares y articulares."},
    {"nombre": "Endocrinología", "descripcion": "Trastornos hormonales y metabólicos."},
    {"nombre": "Gastroenterología", "descripcion": "Enfermedades del sistema digestivo."},
    {"nombre": "Otorrinolaringología", "descripcion": "Enfermedades de oído, nariz y garganta."},
    {"nombre": "Oftalmología", "descripcion": "Salud visual y enfermedades oculares."},
    {"nombre": "Urología", "descripcion": "Tracto urinario y sistema reproductor masculino."},
    {"nombre": "Oncología", "descripcion": "Diagnóstico y tratamiento de cáncer."},
    {"nombre": "Reumatología", "descripcion": "Enfermedades autoinmunes y reumáticas."},
    {"nombre": "Nefrología", "descripcion": "Trastornos y enfermedades renales."},
    {"nombre": "Hematología", "descripcion": "Enfermedades de la sangre y médula ósea."},
    {"nombre": "Medicina General", "descripcion": "Atención primaria y control integral de salud."},
    {"nombre": "Psiquiatría", "descripcion": "Salud mental y tratamiento de trastornos emocionales."},
    {"nombre": "Psicología Clínica", "descripcion": "Evaluación y acompañamiento psicológico."},
    {"nombre": "Nutrición", "descripcion": "Planificación alimentaria y control nutricional."},
    {"nombre": "Fonoaudiología", "descripcion": "Trastornos del habla, voz y audición."},
    {"nombre": "Alergología", "descripcion": "Diagnóstico y control de alergias."},
    {"nombre": "Infectología", "descripcion": "Tratamiento de enfermedades infecciosas."},
    {"nombre": "Neumonología", "descripcion": "Enfermedades respiratorias."},
    {"nombre": "Medicina Deportiva", "descripcion": "Prevención y tratamiento en deportistas."},
    {"nombre": "Cirugía General", "descripcion": "Intervenciones quirúrgicas no especializadas."},
    {"nombre": "Cirugía Plástica", "descripcion": "Reconstructiva y estética."},
    {"nombre": "Anestesiología", "descripcion": "Control del dolor y anestesia en cirugías."},
    {"nombre": "Radiología", "descripcion": "Diagnóstico por imágenes."},
    {"nombre": "Kinesiología", "descripcion": "Rehabilitación física y motora."},
    {"nombre": "Medicina Laboral", "descripcion": "Evaluación médica para aptitud laboral."},
]

for e in especialidades:
    Especialidad.objects.get_or_create(**e)


# === SERVICIOS ===
servicios = [
    {"nombre": "Consulta Presencial", "descripcion": "Atención médica tradicional en consultorio."},
    {"nombre": "Consulta Virtual", "descripcion": "Videollamada mediante plataforma segura."},
    {"nombre": "Guardia 24hs", "descripcion": "Atención inmediata para emergencias leves."},
    {"nombre": "Cirugías Programadas", "descripcion": "Intervenciones quirúrgicas planificadas."},
    {"nombre": "Estudios Diagnósticos", "descripcion": "Análisis clínicos, imágenes y pruebas."},
    {"nombre": "Control de Rutina", "descripcion": "Exámenes periódicos y seguimiento de salud."},
    {"nombre": "Atención Domiciliaria", "descripcion": "Consulta médica en el hogar del paciente."},
    {"nombre": "Rehabilitación Física", "descripcion": "Sesiones de kinesiología y fisioterapia."},
    {"nombre": "Teleorientación Médica", "descripcion": "Asesoría médica rápida y remota."},
    {"nombre": "Salud Mental Online", "descripcion": "Consultas psicológicas o psiquiátricas virtuales."},
]

for s in servicios:
    Servicio.objects.get_or_create(**s)


# === PROFESIONALES ===
profesionales = [
    {
        "nombre": "Dr. Martín Acosta",
        "email": "macosta@clinic.com",
        "matricula": "M-1001",
        "telefono": "11-4321-1001",
        "disponibilidad": "Lunes a Viernes",
        "consultorio": "101",
        "horario_inicio": "08:00",
        "horario_fin": "16:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 1,
    },
    {
        "nombre": "Dra. Laura Fernández",
        "email": "lfernandez@clinic.com",
        "matricula": "M-1002",
        "telefono": "11-4321-1002",
        "disponibilidad": "Lunes a Sábado",
        "consultorio": "102",
        "horario_inicio": "09:00",
        "horario_fin": "17:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 2,
    },
    {
        "nombre": "Dr. Pablo Riquelme",
        "email": "priquelme@clinic.com",
        "matricula": "M-1003",
        "telefono": "11-4321-1003",
        "disponibilidad": "Martes a Sábado",
        "consultorio": "103",
        "horario_inicio": "10:00",
        "horario_fin": "18:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 3,
    },
    {
        "nombre": "Dra. Sofía Duarte",
        "email": "sduarte@clinic.com",
        "matricula": "M-1004",
        "telefono": "11-4321-1004",
        "disponibilidad": "Lunes a Viernes",
        "consultorio": "104",
        "horario_inicio": "08:30",
        "horario_fin": "15:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 4,
    },
    {
        "nombre": "Dr. Hernán López",
        "email": "hlopez@clinic.com",
        "matricula": "M-1005",
        "telefono": "11-4321-1005",
        "disponibilidad": "Lunes a Jueves",
        "consultorio": "105",
        "horario_inicio": "12:00",
        "horario_fin": "20:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue",
        "especialidad_id": 5,
    },
    {
        "nombre": "Dra. Natalia Molina",
        "email": "nmolina@clinic.com",
        "matricula": "M-1006",
        "telefono": "11-4321-1006",
        "disponibilidad": "Martes a Viernes",
        "consultorio": "106",
        "horario_inicio": "07:00",
        "horario_fin": "14:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie",
        "especialidad_id": 6,
    },
    {
        "nombre": "Dr. Tomás Pereyra",
        "email": "tpereyra@clinic.com",
        "matricula": "M-1007",
        "telefono": "11-4321-1007",
        "disponibilidad": "Miércoles a Domingo",
        "consultorio": "107",
        "horario_inicio": "13:00",
        "horario_fin": "21:00",
        "dias_disponibles": "Mie-Jue-Vie-Sab-Dom",
        "especialidad_id": 7,
    },
    {
        "nombre": "Dra. Julieta Sosa",
        "email": "jsosa@clinic.com",
        "matricula": "M-1008",
        "telefono": "11-4321-1008",
        "disponibilidad": "Lunes a Viernes",
        "consultorio": "108",
        "horario_inicio": "14:00",
        "horario_fin": "20:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 8,
    },
    {
        "nombre": "Dr. Ricardo Benítez",
        "email": "rbenitez@clinic.com",
        "matricula": "M-1009",
        "telefono": "11-4321-1009",
        "disponibilidad": "Lunes a Sábado",
        "consultorio": "109",
        "horario_inicio": "08:00",
        "horario_fin": "14:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 9,
    },
    {
        "nombre": "Dra. Paula Godoy",
        "email": "pgodoy@clinic.com",
        "matricula": "M-1010",
        "telefono": "11-4321-1010",
        "disponibilidad": "Martes a Viernes",
        "consultorio": "110",
        "horario_inicio": "10:00",
        "horario_fin": "16:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie",
        "especialidad_id": 10,
    },

    {
        "nombre": "Dr. Diego Villalba",
        "email": "dvillalba@clinic.com",
        "matricula": "M-1011",
        "telefono": "11-4321-1011",
        "disponibilidad": "Lunes-Viernes",
        "consultorio": "201",
        "horario_inicio": "08:00",
        "horario_fin": "16:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 11,
    },
    {
        "nombre": "Dra. Milena Torres",
        "email": "mtorres@clinic.com",
        "matricula": "M-1012",
        "telefono": "11-4321-1012",
        "disponibilidad": "Lunes-Jueves",
        "consultorio": "202",
        "horario_inicio": "09:00",
        "horario_fin": "17:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue",
        "especialidad_id": 12,
    },
    {
        "nombre": "Dr. Facundo Herrera",
        "email": "fherrera@clinic.com",
        "matricula": "M-1013",
        "telefono": "11-4321-1013",
        "disponibilidad": "Martes-Sábado",
        "consultorio": "203",
        "horario_inicio": "12:00",
        "horario_fin": "18:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 13,
    },
    {
        "nombre": "Dra. Antonella Cruz",
        "email": "acruz@clinic.com",
        "matricula": "M-1014",
        "telefono": "11-4321-1014",
        "disponibilidad": "Miércoles-Domingo",
        "consultorio": "204",
        "horario_inicio": "14:00",
        "horario_fin": "20:00",
        "dias_disponibles": "Mie-Jue-Vie-Sab-Dom",
        "especialidad_id": 14,
    },
    {
        "nombre": "Dr. Gonzalo Araya",
        "email": "garaya@clinic.com",
        "matricula": "M-1015",
        "telefono": "11-4321-1015",
        "disponibilidad": "Lunes-Viernes",
        "consultorio": "205",
        "horario_inicio": "09:00",
        "horario_fin": "15:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 15,
    },
    {
        "nombre": "Dra. Verónica Palma",
        "email": "vpalma@clinic.com",
        "matricula": "M-1016",
        "telefono": "11-4321-1016",
        "disponibilidad": "Martes-Viernes",
        "consultorio": "206",
        "horario_inicio": "08:00",
        "horario_fin": "13:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie",
        "especialidad_id": 16,
    },
    {
        "nombre": "Dr. Alejandro Paredes",
        "email": "aparedes@clinic.com",
        "matricula": "M-1017",
        "telefono": "11-4321-1017",
        "disponibilidad": "Miércoles-Domingo",
        "consultorio": "207",
        "horario_inicio": "13:00",
        "horario_fin": "19:00",
        "dias_disponibles": "Mie-Jue-Vie-Sab-Dom",
        "especialidad_id": 17,
    },
    {
        "nombre": "Dra. Mara Cairo",
        "email": "mcairo@clinic.com",
        "matricula": "M-1018",
        "telefono": "11-4321-1018",
        "disponibilidad": "Lunes-Jueves",
        "consultorio": "208",
        "horario_inicio": "10:00",
        "horario_fin": "18:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue",
        "especialidad_id": 18,
    },
    {
        "nombre": "Dr. Nicolás D'Angelo",
        "email": "ndangelo@clinic.com",
        "matricula": "M-1019",
        "telefono": "11-4321-1019",
        "disponibilidad": "Martes-Sábado",
        "consultorio": "209",
        "horario_inicio": "08:00",
        "horario_fin": "14:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 19,
    },
    {
        "nombre": "Dra. Valentina Mena",
        "email": "vmena@clinic.com",
        "matricula": "M-1020",
        "telefono": "11-4321-1020",
        "disponibilidad": "Lunes-Viernes",
        "consultorio": "210",
        "horario_inicio": "11:00",
        "horario_fin": "19:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 20,
    },

    # últimos 5
    {
        "nombre": "Dr. Fabián Navarro",
        "email": "fnavarro@clinic.com",
        "matricula": "M-1021",
        "telefono": "11-4321-1021",
        "disponibilidad": "Lunes-Viernes",
        "consultorio": "301",
        "horario_inicio": "08:00",
        "horario_fin": "14:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie",
        "especialidad_id": 21,
    },
    {
        "nombre": "Dra. Camila Tevez",
        "email": "ctevez@clinic.com",
        "matricula": "M-1022",
        "telefono": "11-4321-1022",
        "disponibilidad": "Martes-Sábado",
        "consultorio": "302",
        "horario_inicio": "10:00",
        "horario_fin": "17:00",
        "dias_disponibles": "Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 22,
    },
    {
        "nombre": "Dr. Sergio Domínguez",
        "email": "sdominguez@clinic.com",
        "matricula": "M-1023",
        "telefono": "11-4321-1023",
        "disponibilidad": "Miércoles-Domingo",
        "consultorio": "303",
        "horario_inicio": "12:00",
        "horario_fin": "20:00",
        "dias_disponibles": "Mie-Jue-Vie-Sab-Dom",
        "especialidad_id": 23,
    },
    {
        "nombre": "Dra. Marina Roldán",
        "email": "mroldan@clinic.com",
        "matricula": "M-1024",
        "telefono": "11-4321-1024",
        "disponibilidad": "Lunes-Jueves",
        "consultorio": "304",
        "horario_inicio": "14:00",
        "horario_fin": "20:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue",
        "especialidad_id": 24,
    },
    {
        "nombre": "Dr. Darío Ramírez",
        "email": "dramirez@clinic.com",
        "matricula": "M-1025",
        "telefono": "11-4321-1025",
        "disponibilidad": "Lunes-Sábado",
        "consultorio": "305",
        "horario_inicio": "09:00",
        "horario_fin": "17:00",
        "dias_disponibles": "Lun-Mar-Mie-Jue-Vie-Sab",
        "especialidad_id": 25,
    },
]

for p in profesionales:
    Profesional.objects.get_or_create(**p)

print("✔ Datos cargados correctamente.")
