# Generated by Django 5.2.8 on 2025-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frecuenciacardiaca',
            options={'verbose_name': 'Frecuencia Cardíaca', 'verbose_name_plural': 'Frecuencias Cardíacas'},
        ),
        migrations.AlterModelOptions(
            name='frecuenciarespiratoria',
            options={'verbose_name': 'Frecuencia Respiratoria', 'verbose_name_plural': 'Frecuencias Respiratorias'},
        ),
        migrations.AlterModelOptions(
            name='indicaciones',
            options={'verbose_name': 'Indicación', 'verbose_name_plural': 'Indicaciones'},
        ),
        migrations.AlterModelOptions(
            name='pesoaltura',
            options={'verbose_name': 'Peso y Altura', 'verbose_name_plural': 'Pesos y Alturas'},
        ),
        migrations.AlterModelOptions(
            name='presionarterial',
            options={'verbose_name': 'Presión Arterial', 'verbose_name_plural': 'Presiones Arteriales'},
        ),
        migrations.AlterModelOptions(
            name='saturacionoxigeno',
            options={'verbose_name': 'Saturación de Oxígeno', 'verbose_name_plural': 'Saturaciones de Oxígeno'},
        ),
    ]
