# Generated by Django 5.2.5 on 2025-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_alter_frecuenciacardiaca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesoaltura',
            name='hora',
            field=models.TimeField(auto_now_add=True, default="12:00"),
            preserve_default=False,
        ),
    ]
