# Generated by Django 5.2.5 on 2025-11-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsoAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('antes_del_turno', models.BooleanField(default=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenities.amenity')),
            ],
            options={
                'verbose_name': 'Uso de Amenity',
                'verbose_name_plural': 'Usos de Amenities',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
