# Generated by Django 5.2.5 on 2025-11-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_initial'),
        ('pacientes', '0004_estudio_mensaje'),
        ('turnos', '0008_checkinlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='amenities.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioOtorgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amenities.beneficio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_recibidos', to='pacientes.paciente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios_otorgados', to='turnos.turno')),
            ],
        ),
    ]
