# Generated by Django 5.2.5 on 2026-02-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0003_beneficio_beneficiootorgado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='beneficiootorgado',
            options={'verbose_name': 'Beneficio Otorgado', 'verbose_name_plural': 'Beneficios Otorgados'},
        ),
    ]
