# Generated by Django 5.2.8 on 2025-11-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_profesional_piso'),
        ('turnos', '0003_alter_turno_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='piso',
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='turnos.estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.servicio'),
        ),
    ]
