# Generated by Django 5.2.5 on 2025-11-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_remove_turno_piso_alter_turno_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='servicio',
        ),
    ]
