# Generated by Django 5.2.8 on 2025-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_remove_turno_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('PRES', 'Presencial'), ('TELE', 'Teleconsulta')], max_length=5, null=True),
        ),
    ]
