# Generated by Django 5.2.8 on 2025-11-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_turno_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(choices=[('PRES', 'Presencial'), ('TELE', 'Teleconsulta')], default='PRES', max_length=10),
        ),
    ]
