# Generated by Django 5.2.5 on 2026-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_checkinlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
    ]
