# Generated by Django 5.2.5 on 2025-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliado', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('obra_social', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
