# Generated by Django 5.2.5 on 2025-11-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='perfil_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_asociados', to='usuarios.perfilusuario'),
        ),
    ]
