# Generated by Django 5.2.5 on 2025-11-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_afiliado',
        ),
    ]
