# Generated by Django 5.2.5 on 2026-02-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_paciente_dni'),
        ('usuarios', '0002_remove_perfilusuario_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='perfil_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='usuarios.perfilusuario'),
        ),
    ]
